apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-deployment
  annotations:
    kubernetes.io/change-cause: rs1     # deployment를 롤백시켜주는 애너테이션
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather-server
        image: docker.io/mskim6518/argocd-k8s:weather-0.0.3-43
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weather-svc-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: weather

