name: BuildAndPushImages

#main에 푸쉬된 경우 action.yml에 작성한 내용 수행
on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_REPO: mskim6518/argocd-k8s
  VERSION : 0.0.3

jobs:
  ci_cd_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: source code checkout
        # uses의 경우 Marketplace에 사전 정의된 내용을 이용하여 step 수행 
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Log in to Docker hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 서버 이미지 빌드 및 푸시
        id: build_and_push_server
         # run의 경우 직접 기재한 커맨드 수행 
        run: |
           echo ${{ secrets.ENV_SECRET }} > .env
           docker build --platform linux/arm64 -f Dockerfile -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}:weather-${{ env.VERSION }}-${{ github.run_number }} .
           docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}:weather-${{ env.VERSION }}-${{ github.run_number }}
