name: BuildAndPushImages

#main에 푸쉬된 경우 action.yml에 작성한 내용 수행
on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_REPO: mskim6518/argocd-k8s
  VERSION : 0.0.3

jobs:
  ci_cd_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: source code checkout
        # uses의 경우 Marketplace에 사전 정의된 내용을 이용하여 step 수행 
        uses: actions/checkout@v3
        
      - name: Copy Secret variable
        env:
          ENV_SECRET: ${{ secrets.ENV_SECRET }}
          ENV_SECRET_DIR: src/main/resources
          ENV_SECRET_DIR_FILE_NAME: .env
        run:
          echo $ENV_SECRET | base64 --decode > $ENV_SECRET_DIR/$ENV_SECRET_DIR_FILE_NAME
 
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Log in to Docker hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: 서버 이미지 빌드 및 푸시
        id: build_and_push_server
         # run의 경우 직접 기재한 커맨드 수행 
        run: |
           docker build --platform linux/arm64 -f Dockerfile -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}:weather-${{ env.VERSION }}-${{ github.run_number }} .
           docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}:weather-${{ env.VERSION }}-${{ github.run_number }}
      - name: Update Kubernetes manifest
        run: |
          sed -i 's#image:.*#image: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_REPO }}:weather-${{ env.VERSION }}-${{ github.run_number }}#' ./weather.yml
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "minorchy@naver.com"
          git config --global user.name "DevelopIsHobby"
          git pull --rebase origin main 
          git add ./weather.yml
          git commit -m "Update Kubernetes manifest with new Docker image"
          git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/${{ github.repository }}.git HEAD:main
